{{- range .Values.frontends }}
apiVersion: v1
# Ther services for the frontend pods.
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .exposePort }}
  selector:
    app: {{ .name }}
---
{{- end }}

{{- range .Values.backends }}
apiVersion: v1
# The services for the backend pods.
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .exposePort }}
  selector:
    app: {{ .name }}
---
{{- end }}