version: "3.8"
services:
  login-backend:
    container_name: login-backend
    image: ghcr.io/gamify-it/login-backend:main
    ports:
      - "4000:4000"
    environment:
      - JWT_KEY=SecretKEY
      - POSTGRES_URL=postgresql://postgres:super_secure_password@login-db:5432/postgres
  login-frontend:
    container_name: login-frontend
    image: ghcr.io/gamify-it/login-frontend:v0.0.2
    ports:
      - "8000:8000"
  overworld:
    container_name: overworld
    image: ghcr.io/gamify-it/overworld-demo:v0.0.4
    ports:
      - "1234:1234"
  git-card-game:
    container_name: git-card-game
    image: ghcr.io/gamify-it/git-card-game:main
    ports:
      - "7001:7001"
  login-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secure_password
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  db:
    driver: local
