version: "3.8"
services:
  login-backend:
    container_name: login-backend
    image: ghcr.io/gamify-it/login-backend:main
    ports:
      - "8080:8080"
  login-frontend:
    container_name: login-frontend
    image: ghcr.io/gamify-it/stupro-login-demo:main
    ports:
      - "8000:8000"
  overworld:
    container_name: overworld-demo
    image: ghcr.io/gamify-it/overworld-demo:v0.0.2
    ports:
      - "1234:80"
  git-card-game:
    container_name: git-card-game
    image: ghcr.io/gamify-it/git-card-game:main
    ports:
      - "7001:8000"
  login-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secure_password

volumes:
  db:
    driver: local
