apiVersion: v1
kind: Secret
# Admin username and password base64 encoded
metadata:
  name: keycloak-admin-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_USERNAME }}       
  KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
