kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-bugfinder-db-pv
  labels:
    type: local
    app: gamify-it-bugfinder-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/bugfinder-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-chickenshock-db-pv
  labels:
    type: local
    app: gamify-it-chickenshock-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/chickenshock-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-crosswordpuzzle-db-pv
  labels:
    type: local
    app: gamify-it-crosswordpuzzle-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/crosswordpuzzle-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-finitequiz-db-pv
  labels:
    type: local
    app: gamify-it-finitequiz-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/finitequiz-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-keycloak-db-pv
  labels:
    type: local
    app: gamify-it-keycloak-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/keycloak-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-memory-db-pv
  labels:
    type: local
    app: gamify-it-memory-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/memory-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-overworld-db-pv
  labels:
    type: local
    app: gamify-it-overworld-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/overworld-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-regexgame-db-pv
  labels:
    type: local
    app: gamify-it-regexgame-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/regexgame-db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamify-it-towercrush-db-pv
  labels:
    type: local
    app: gamify-it-towercrush-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/towercrush-db"
---

