version: "3.7"

services:

  #databases
  setup:
    container_name: setup
    image: ghcr.io/gamify-it/test-data:latest
    pull_policy: always
    restart: on-failure
    environment:
      POSTGRES_SETUP: >
        bugfinder/default.sql
        chickenshock/default.sql
        finitequiz/default.sql
        keycloak/default.sql
        overworld/default.sql
        crosswordpuzzle/default.sql            

  keycloak-db:
    container_name: keycloak-db
    image: postgres:14-alpine
    pull_policy: always
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  fileserver-db:
    container_name: fileserver-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    volumes:
      - ./data/fileserver-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  overworld-db:
    container_name: overworld-db
    image: postgres:14-alpine
    pull_policy: always
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  chickenshock-db:
    container_name: chickenshock-db
    image: postgres:14-alpine
    pull_policy: always
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  crosswordpuzzle-db:
    container_name: crosswordpuzzle-db
    image: postgres:14-alpine
    pull_policy: always
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  finitequiz-db:
    container_name: finitequiz-db
    image: postgres:14-alpine
    pull_policy: always
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  bugfinder-db:
    container_name: bugfinder-db
    image: postgres:14-alpine
    pull_policy: always
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  memory-db:
    container_name: memory-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    volumes:
    - ./data/memory-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  towercrush-db:
    container_name: towercrush-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    volumes:
    - ./data/towercrush-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #backends
  keycloak:
    container_name: keycloak
    expose:
      - "80"
    image: quay.io/keycloak/keycloak:19.0
    pull_policy: always
    restart: always
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HOSTNAME_URL: http://${url}/keycloak
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HTTP_PORT: 80

  fileserver:
    container_name: fileserver
    image: ghcr.io/gamify-it/sharry-fileserver:main
    restart: always
    expose:
      - "80"
    volumes:
      - ./data/fileserver-storage:/storage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://fileserver-db:5432/postgres
      - BASE_URL=${url}
      - KEYCLOAK_CLIENT_ID=fileserver
      - KEYCLOAK_CLIENT_SECRET=${fileserver_keycloak_client_secret}
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  overworld-backend:
    container_name:   overworld-backend
    image: ghcr.io/gamify-it/overworld-backend:main
    pull_policy: always
    restart: always
    expose:
      - "80"
    depends_on:
      - overworld-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://overworld-db:5432/postgres
      - CHICKENSHOCK_URL=http://chickenshock-backend/api/v1
      - CROSSWORDPUZZLE_URL=http://crosswordpuzzle-backend/api/v1
      - FINITEQUIZ_URL=http://finitequiz-backend/api/v1
      - BUGFINDER_URL=http://bugfinder-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  crosswordpuzzle-backend:
    container_name:   crosswordpuzzle-backend
    image: ghcr.io/gamify-it/crosswordpuzzle-backend:main
    pull_policy: always
    restart: always
    expose:
      - "80"
    depends_on:
      - crosswordpuzzle-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://crosswordpuzzle-db:5432/postgres
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  chickenshock-backend:
    container_name:   chickenshock-backend
    image: ghcr.io/gamify-it/chickenshock-backend:main
    pull_policy: always
    restart: always
    expose:
      - "80"
    depends_on:
      - chickenshock-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://chickenshock-db:5432/postgres
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  finitequiz-backend:
    container_name:   finitequiz-backend
    image: ghcr.io/gamify-it/finitequiz-backend:main
    pull_policy: always
    restart: always
    expose:
      - "80"
    depends_on:
      - finitequiz-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://finitequiz-db:5432/postgres
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  bugfinder-backend:
    container_name:   bugfinder-backend
    image: ghcr.io/gamify-it/bugfinder-backend:main
    pull_policy: always
    restart: always
    expose:
      - "80"
    depends_on:
      - bugfinder-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://bugfinder-db:5432/postgres
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  memory-backend:
    container_name:   memory-backend
    image: ghcr.io/gamify-it/memory-backend:main
    restart: always
    expose:
      - "80"
    depends_on:
      - memory-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://memory-db:5432/postgres
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT

  towercrush-backend:
    container_name:   towercrush-backend
    image: ghcr.io/gamify-it/towercrush-backend:main
    restart: always
    expose:
      - "80"
    depends_on:
      - bugfinder-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://towercrush-db:5432/postgres
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - KEYCLOAK_ISSUER=${url}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT


  #frontends
  landing-page:
    container_name: landing-page
    image: ghcr.io/gamify-it/landing-page:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  overworld:
    container_name: overworld
    image: ghcr.io/gamify-it/overworld:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  git-card-game:
    container_name: git-card-game
    image: ghcr.io/gamify-it/git-card-game:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  chickenshock:
    container_name: chickenshock
    image: ghcr.io/gamify-it/chickenshock:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  crosswordpuzzle:
    container_name: crosswordpuzzle
    image: ghcr.io/gamify-it/crosswordpuzzle:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  regex-game:
    container_name: regex-game
    image: ghcr.io/gamify-it/regex-game:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  bugfinder:
    container_name: bugfinder
    image: ghcr.io/gamify-it/bugfinder:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  memory:
    container_name: memory
    image: ghcr.io/gamify-it/memory:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  lecturer-interface:
    container_name: lecturer-interface
    image: ghcr.io/gamify-it/lecturer-interface:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  finitequiz:
    container_name: finitequiz
    image: ghcr.io/gamify-it/finitequiz:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  towercrush:
    container_name: towercrush
    image: ghcr.io/gamify-it/towercrush:main
    restart: always
    expose:
      - "80"

  third-party-license-notice:
    container_name: third-party-license-notice
    image: ghcr.io/gamify-it/third-party-license-notice:main
    pull_policy: always
    restart: always
    expose:
      - "80"

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    pull_policy: always
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl-certs:/etc/nginx/ssl-certs:ro
    ports:
      - "${http_port}:${http_port}"
