version: "3.8"

# This compose file uses fragments and extensions
# For more information please read the documentation
#     https://docs.docker.com/compose/compose-file/11-extension
#     https://docs.docker.com/compose/compose-file/10-fragments

x-templates:
  template-service: &template-service
    restart: unless-stopped
    pull_policy: always

services: 

  template-service:
    <<: *template-service

  template-backend:
    <<: *template-service
    environment:
      - BUGFINDER_URL=http://bugfinder-backend/api/v1
      - CHICKENSHOCK_URL=http://chickenshock-backend/api/v1
      - CROSSWORDPUZZLE_URL=http://crosswordpuzzle-backend/api/v1
      - FINITEQUIZ_URL=http://finitequiz-backend/api/v1
      - KEYCLOAK_ISSUER=${EXTERNAL_URL}/keycloak/realms/Gamify-IT
      - KEYCLOAK_URL=http://keycloak/keycloak/realms/Gamify-IT
      - OVERWORLD_URL=http://overworld-backend/api/v1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "80"

  template-db:
    <<: *template-service
    image: postgres:14-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  template-frontend:
    <<: *template-service
    expose:
      - "80"
